name: Python Unittests

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Create Logs Directory
      run: |
        mkdir -p $HOME/logs/scheduler
        chmod -R 777 $HOME/logs
    
    - name: Initialize Airflow Database
      run: |
        export AIRFLOW_HOME=$(pwd)
        airflow db init

    - name: Start Airflow Scheduler
      run: |
          airflow scheduler

    - name: Check for dag list
      run: |
        airflow dags list

    - name: Trigger pipeline
      run: |
        airflow dags trigger -e 2023-11-11 pipeline

    - name: Run unittests
      run: python -m unittest test.test_unittest

    - name: Stop Docker Compose
      run: docker-compose down

    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"