name: Python Unittests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Initialize Airflow Database
      run: |
        airflow db init

    - name: Start Airflow Web Server
      run: |
          airflow webserver -p 8080 &
          sleep 10

    - name: Start Airflow Scheduler
      run: |
          airflow scheduler &
          sleep 10

    - name: Check for dag list
      run: |
        airflow dags list

    - name: Trigger pipeline
      run: |
        airflow dags trigger pipeline

    - name: Run unittests
      run: python -m unittest test.test_unittest

    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"